# SPDX-FileCopyrightText: 2020 Open Networking Foundation <info@opennetworking.org>
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
#
name: Prettify

on:
  push:
    branches:
      - java-prettify

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        # Recommended: latest versions of Google Java Format require JDK 11+
        java-version: "11"
    - name: Run yapf
      run: make prettify
    - name: Run Google Java Format
      uses: axel-op/googlejavaformat-action@v3
      with:
        skipCommit: true
        args: "--replace"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.7.0
      with:
        commit-message: Auto-prettify ${{ github.sha }}
        title: Auto-prettify 💅
        labels: prettybot
        branch: prettybot-java-test
